# Generated by Django 2.2.7 on 2019-11-24 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patologias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patologia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patologia',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AlterField(
            model_name='patologia',
            name='nombre',
            field=models.CharField(max_length=128, unique=True, verbose_name='Nombre de Patología'),
        ),
    ]
