# Generated by Django 2.2.7 on 2019-11-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patologias', '0002_auto_20191124_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patologia',
            options={'ordering': ['nombre'], 'verbose_name': 'Patología', 'verbose_name_plural': 'Patologías'},
        ),
    ]
