# Generated by Django 2.2.7 on 2019-12-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={'ordering': ['nombres'], 'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='nombre',
        ),
        migrations.AddField(
            model_name='profesional',
            name='nombres',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesional',
            name='primer_apellido',
            field=models.CharField(default='', max_length=50, verbose_name='Primer Apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesional',
            name='run',
            field=models.CharField(default='', max_length=10, verbose_name='RUN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesional',
            name='segundo_apellido',
            field=models.CharField(default='', max_length=50, verbose_name='Segundo Apellido'),
            preserve_default=False,
        ),
    ]
