# Generated by Django 2.2.7 on 2019-11-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='nombre',
            field=models.CharField(max_length=254, verbose_name='Nombre de establecimiento'),
        ),
    ]
