# Generated by Django 2.2.7 on 2019-11-24 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellidos',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dv',
            field=models.CharField(max_length=1, verbose_name='Dígito Verificador'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='run',
            field=models.CharField(max_length=200, unique=True, verbose_name='RUN'),
        ),
    ]
