# Generated by Django 2.2.7 on 2019-11-24 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20191124_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
