# Generated by Django 2.2.7 on 2019-11-29 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0005_auto_20191124_1854'),
        ('patologias', '0003_auto_20191124_1657'),
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite')),
                ('observacion', models.TextField(verbose_name='Observación')),
                ('vigente', models.BooleanField(default=True, verbose_name='Caso Vigente')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='establecimientos.Establecimiento', verbose_name='Establecimiento Responsable')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente', verbose_name='Paciente')),
                ('patologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patologias.Patologia', verbose_name='Patología')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'ordering': ['fecha_limite'],
            },
        ),
    ]
