# Generated by Django 2.2.7 on 2019-12-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='exceptuado',
            field=models.BooleanField(default=False, verbose_name='Caso Exceptuado'),
        ),
    ]
