# Generated by Django 2.2.7 on 2019-11-24 19:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caso',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='fecha_limite',
            field=models.DateField(verbose_name='Fecha Límite'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.Paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='patologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patologias.Patologia', verbose_name='Patología'),
        ),
    ]
