# Generated by Django 2.2.7 on 2019-11-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_auto_20191124_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caso',
            options={'ordering': ['-fecha_limite'], 'verbose_name': 'Caso', 'verbose_name_plural': 'Casos'},
        ),
    ]
