# Generated by Django 2.2.7 on 2019-11-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_auto_20191124_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='observacion',
            field=models.TextField(default='', verbose_name='Observación'),
            preserve_default=False,
        ),
    ]
