# Generated by Django 2.2.7 on 2019-11-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0004_caso_observacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caso',
            options={'ordering': ['fecha_limite'], 'verbose_name': 'Caso', 'verbose_name_plural': 'Casos'},
        ),
        migrations.AddField(
            model_name='caso',
            name='vigente',
            field=models.BooleanField(default=True, verbose_name='Caso Vigente'),
        ),
    ]
